export { authAPI } from './auth'
export { registrationAPI } from './registration'
export { consultationsAPI } from './consultations'
export { profileAPI } from './profile'
export { visitsAPI } from './visits'
export { settingsAPI } from './settings'
